### ISSUE TITLE
맥주 상세화면 조회 > 홈 화면 이동시 스크롤 초기화 증상

### ISSUE THREAD

**Issue by mgmix** [DDD-4/Synesthesia-Android#76]
- 증상 
맥주 목록에서 상세 화면 이동 후  뒤로가기로 다시 맥주 목록을 돌아왔을 때, 마지막 포지션으로 위치하지 못하고 상단으로 스크롤이 옮겨짐

**Comment by mgmix** [comment]
홈 화면에서 - > 상세 화면 진입 후 -> 뒤로가기 시에 홈 화면의 View 가 destroy 되었다가 다시 recreate 되는 과정에서 필터링 및 데이터 로드하는 observer trigger 발생

**Comment by hjiee** [comment]
상세화면을 activity로 전환하면서 해당 문제 수정하였습니다.
